### ISSUE TITLE
Remove your name from repo name

### ISSUE THREAD

**Issue by ff6347** [Ninotschka/Nina_Komarova-Zelinskaya-outlines#1]
You don't need to add your name to the project title. It is already under your account. Looks wired. :)

**Comment by Ninotschka** [comment]
yea, i had a funny feeling about it :) 

( now i just have to figure out how to actually make the website work and then change the name :) )

**Comment by ff6347** [comment]
You can change the name under the settings of the repo

**Comment by ff6347** [comment]
to make it work you'll have to change one line in index.html line 12

change it from 

```
  <script type="text/javascript" src="lib/p5.min.js"></script>
```

to

```
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.4.17/p5.min.js></script>
```

**Comment by ff6347** [comment]
Another thing. You deleted your master branch. You can set your gh-pages branch as the primary branch. This can also be done in the settings.  

go to https://github.com/Ninotschka/Nina_Komarova-Zelinskaya-outlines/settings

There is left a tab with "options". There you can change the name
and another tab  called "branches" there you can set the primary branch to be your gh-pages branch

**Comment by ff6347** [comment]
Sorry not primary. its default branch 

![bildschirmfoto 2015-11-17 um 17 47 20](https://cloud.githubusercontent.com/assets/315106/11217981/53756424-8d53-11e5-9ccd-13a32ed29a19.png)

**Comment by Ninotschka** [comment]
changed the line, it is better then before: it shows the changed line in the new window

( about the master branch- that was a not so tragic but an accident - but i am not sure i need it eitherway)

**Comment by ff6347** [comment]
again sorry. Wrong link go to https://github.com/Ninotschka/Nina_Komarova-Zelinskaya-outlines/settings

**Comment by ff6347** [comment]
there is a 

```
<script ...
```

missing at the beginnig of the line :-)

not  

```
script ...
```

**Comment by ff6347** [comment]
```
< 
```

is missing

**Comment by Ninotschka** [comment]
tricky. changed it. still not working. gonna try to copy the line again,apparently i need 3 trys for this simple action.

**Comment by Ninotschka** [comment]
unfortunately it stil doesn't work :(

**Comment by ff6347** [comment]
see #2

**Comment by ff6347** [comment]
its just one " missing

**Comment by Ninotschka** [comment]
( copied and replaced from #2 ) 

maybe i am blind but i do see only one of those " there...

**Comment by ff6347** [comment]
now it works
http://ninotschka.github.io/outlines/

it was at the end of src="http://.....p5.min.js > after the js. That was missing

**Comment by Ninotschka** [comment]
it does work!!!!!

thank you so much!!!
